### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by deva-gopalani** [danishm/mritopng#20]
After running the code on a folder consisting of the DICOM images, the DICOM images get converted into a format of .dcm.png. Is it not possible to get the image in only .png form?

**Comment by danishm** [comment]
@deva-gopalani Yes, it's possible. Is this an urgent need?

**Comment by deva-gopalani** [comment]
@danishm, yes it is. Required it for a project.

**Comment by danishm** [comment]
@deva-gopalani Alright, I'll try to get it done over the weekend

**Comment by deva-gopalani** [comment]
@danishm, that would be great! Thank you!
