### ISSUE TITLE
Conversion works but...

### ISSUE THREAD

**Issue by Zibri** [danishm/mritopng#22]
Is there a way to increase the resolution or the conversion already happens in the best available from the file?

**Comment by danishm** [comment]
@Zibri `mritopng` doesn't play around with the resolution at all. It does a simple pixel to pixel conversion. Hence, the resolution of the `png` file should match what was inside the `dicom` file. 

Do you feel your source files has better resolution and `mritopng` is not outputting that?

**Comment by Zibri** [comment]
Not at all. I was wondering if by any reason those medical scans had
multiple resolutions inside the file (like GIF for example).The dicom
directory of a dental scan is only 142 MB.
Nevermind... you can close this. And thanks.
