### ISSUE TITLE
confuse about your project?

### ISSUE THREAD

**Issue by Aliktk** [danishm/mritopng#29]
hello sir
as you named it **mritopng** it means that this repo will convert all mri images wheater its in nifty, or nii or nii.gz extension will convertible??
I have images from ADNI and I want to convert it to a series of png or tiff or jog and than pass through my modal so kindly guide me please in this situation if I am using wrong repo than please correct me thanks and jazakAllah

**Comment by danishm** [comment]
Hi @Aliktk 

The repository currently only support conversion from DICOM to PNG. It doesn't have support for nifty.

I'm sorry the name of the repository misled you. It's meant to be a place where people can collaborate and add more functionality, hence I hope we will eventually have support for other formats.
