### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by jafffy** [danishm/mritopng#3]
I wanna fork your project and republish with some additional components, but I don't know your project's license.

Would you like to tell us what license you follow or how much cover reusability of your library (e.g. research purpose, profit purpose...)?

**Comment by danishm** [comment]
Hey, I added an MIT license to it, hoping to make it as open as possible for people to benefit from. Does this work for you?

**Comment by jafffy** [comment]
Yeah, It’s great for me! Thanks a lot!

**Comment by danishm** [comment]
Ok great! Please send me a PR if you'd like to contribute back some of your work.

**Comment by jafffy** [comment]
I’ll do that if I find some points! (But, now it works very well on my purpose :)
