### ISSUE TITLE
Failed conversion should not create a png file

### ISSUE THREAD

**Issue by danishm** [danishm/mritopng#7]
**Actual:** When converting a folder structure, a failed conversion still produces an empty png file. 
**Expected:** There should be no png file for failed conversions

**Comment by kshitij12345** [comment]
Can I take the issue?

**Comment by danishm** [comment]
@kshitij12345 I know it's been over a year since you posted "Can I take the issue?". Have you already fixed this?

**Comment by kshitij12345** [comment]
Yes I believe I do. Will send a PR.

**Comment by danishm** [comment]
@kshitij12345 PR looks mostly good, just requested a simple change on it.

**Comment by danishm** [comment]
Thank you @kshitij12345 !
